# Generated by Django 4.1.5 on 2023-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="2000-08-23"),
            preserve_default=False,
        ),
    ]
